export {default as Header} from "./Header"
export {default as Hero} from "./Hero"
export {default as Tagline} from "./Tagline"
export {default as Features} from "./Features"
export {default as Applications} from "./Applications"
export {default as Faq} from "./Faq"
export {default as Waitlists} from "./Waitlists"
export {default as Footer} from "./Footer"